apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme-namespace

labels:
- includeSelectors: true
  pairs:
    app: acme-hello-api

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: acme-hello-api
    newName: acme-hello-api
    newTag: latest