apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme-namespace

labels:
- includeSelectors: true
  pairs:
    app: acme-hello-api

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # used for auth to cluster from e.g. CICD pipeline
  - role.yaml
  - serviceaccount.yaml
  - sa_secret.yaml
  - rolebinding.yaml

images:
  - name: acme-hello-api
    newName: acme-hello-api
    newTag: latest