# TODO: how to avoid using long lived secrets
apiVersion: v1
kind: Secret
metadata:
  name: my-long-lived-secret
  namespace: acme-namespace
  annotations:
    kubernetes.io/service-account.name: admin-sa
type: kubernetes.io/service-account-token