# Note requires secrets to be added to pipeline
name: Release to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch: # allow manual triggering from GH UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release-k8 # GH Actions environment needed by this pipeline that contains secrets
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DIGITALOCEAN_K8_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8

      - name: Restart Deployments
        run: |
          kubectl rollout restart deployment -n acme-namespace