# Note requires secrets to be added to pipeline
name: Release to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release-k8
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: ${{ secrets.K8S_SERVER }}
              certificate-authority-data: ${{ secrets.K8S_CA_CERT }}
            name: k8s-cluster
          contexts:
          - context:
              cluster: k8s-cluster
              user: admin-sa
            name: admin-sa-context
          current-context: admin-sa-context
          users:
          - name: admin-sa
            user:
              token: ${{ secrets.K8S_TOKEN }}
          " > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8

      - name: Restart Deployments
        run: |
          kubectl rollout restart deployment -n acme-namespace